# Generated by Django 4.2.11 on 2024-04-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0002_recipient_city_recipient_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='network',
            field=models.CharField(choices=[('MTN', 'MTN'), ('Airtel', 'Airtel')], max_length=50),
        ),
    ]
