# Generated by Django 4.2.9 on 2024-04-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_from', models.CharField(max_length=3)),
                ('currency_to', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('currency_from', 'currency_to')},
            },
        ),
    ]
