# Generated by Django 4.2.9 on 2024-03-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='receiver',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='description',
        ),
        migrations.AddField(
            model_name='transfer',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
